<?php

/**
 * Generated by Crude CRUD generator for Fuel on
 * November 25, 2011, 4:57 am
 *
 * @file      classes\model\docmk.php
 * @database  fuel_dev
 * @type      mysql
 * @table     docmk
 * @stencil   activeapp
 */


class Model_DocMK extends Orm\Model {

	// define table name
	protected static $_table_name = 'docmk';

	// define primary key
    protected static $_primary_key = array('id');

	// define table columns
	protected static $_properties = array(
		'id',
		'mk_no' => array(
			'data_type' => 'string', 
			'validation' => array('required')
		),
		'mk_date' => array(
			'data_type' => 'string', 
			'validation' => array('required')
		),
		'client_id' => array(
			'data_type' => 'string', 
			'validation' => array('required', 'numeric_min' => array(1))
		),
		'client_po',
		'delivery_date',
		'deliver_to',
		'delivered_date',
		'product_type' => array(
			'data_type' => 'string', 
			'validation' => array('required')
		),
		'belt_type' => array(
			'data_type' => 'string', 
			'validation' => array('required', 'numeric_min' => array(1))
		),
		'belt_color' => array(
			'data_type' => 'string', 
			'validation' => array('required')
		),
		'belt_color_other',
		'belt_width' => array(
			'data_type' => 'string', 
			'validation' => array('required')
		),
		'belt_width_unit',
		'belt_ply' => array(
			'data_type' => 'string', 
			'validation' => array('required')
		),
		'belt_ep' => array(
			'data_type' => 'string', 
			'validation' => array('required', 'numeric_min' => array(1))
		),
		'belt_grade' => array(
			'data_type' => 'string', 
			'validation' => array('required', 'numeric_min' => array(1))
		),
		'belt_top_grade',
		'belt_bot_grade',
		'belt_thick' => array(
			'data_type' => 'string', 
			'validation' => array('required', 'numeric_min' => array(5))
		),
		'belt_top_thick' => array(
			'data_type' => 'string', 
			'validation' => array('required')
		),
		'belt_bot_thick' => array(
			'data_type' => 'string', 
			'validation' => array('required')
		),
		'belt_length' => array(
			'data_type' => 'string', 
			'validation' => array('required')
		),
		'belt_length_unit',
		'belt_end' => array(
			'data_type' => 'string', 
			'validation' => array('required', 'numeric_min' => array(1))
		),
		'belt_qty' => array(
			'data_type' => 'string', 
			'validation' => array('required', 'numeric_min' => array(1))
		),
		'price_info',
		'belt_price',
		'belt_disc1',
		'belt_disc2',
		'belt_disc3',
		'belt_price_net',
		'belt_amount',
		'remark',
		'creator_id',
		'creator_name',
		'status',
		'created_at',
		'updated_at',
	);

	protected static $_observers = array(
		'Orm\Observer_CreatedAt' => array(
			'events' => array('before_insert'),
		),
		'Orm\Observer_UpdatedAt' => array(
			'events' => array('before_save'),
		),
	);
}